# The three programs, built together. Generated by tools/make-projects.py.
#
#   make -f workspace.mk           what the editor drives, then the editor
#   make -f workspace.mk bin       and all four binaries in bin/
#   make -f workspace.mk check     and run every suite
#   make -f workspace.mk clean
#
# This is the Linux half of what RIDE.xcworkspace is on a Mac and
# RIDE.sln is on Windows: one thing to build, with ed1 after the two
# compilers it drives. It does not reimplement any of their builds - it calls
# the Makefile each repository already has, which is the only way this can stay
# true when one of them changes.
#
# The four are expected side by side. That is the one assumption here, and it
# is the same one the workspace and the solution make.

# Overridable, because they are not called this everywhere. On the Linux box
# the same two repositories are ~/ansicc and ~/shalimar:
#
#   make -f workspace.mk CC1_DIR=$HOME/ansicc SHC_DIR=$HOME/shalimar
# 3.5: the compilers are the VM6747 line - c90 and cpp11 with the three
# host targets and the TMS320C6747, shalimar with its three - and vm6747, the
# emulator that runs the fourth, is built with them. Compiler-C, C++ and
# Compiler-S stay sealed beside.
CC1_DIR ?= ../VM6747/Compiler-Ci
SHC_DIR ?= ../VM6747/Compiler-Si
C2S_DIR ?= ../Converter-C2S
CXX1_DIR ?= ../VM6747/Compiler-Cppi
VM_DIR ?= ../VM6747/Emulator
ASM_DIR ?= ../ASM6x
MASM_DIR ?= ../MASM
LINK_DIR ?= ../LINK
LNK6X_DIR ?= ../LNK6x
# 5.0: the C6747 simulator, which runs a linked .out as TI's does, beside the emulator.
SIM_DIR ?= ../SIM6747
# 5.1: RTS6x, the project's own C6747 runtime, which a TI program links against instead of TI's.
RTS_DIR ?= ../RTS6x

# ---- one directory, named once and given to all four ------------------------
#
# Each of the four Makefiles takes a BINDIR saying where its finished program
# goes, and each defaults to its own repository - so building any one of them
# alone is exactly what it always was. This is the only place that overrides
# the four at once, because this is the only build that knows all four exist.
#
# The default is RIDE's own root, which is where RIDE.exe is built and
# therefore the directory the editor searches first: it finds the compilers it
# drives with path::besideProgram, before PATH, so that a compiler shipped with
# this copy is the one this copy runs.
#
# **Built into, not collected into.** The rule this replaces built the three in
# three places and copied them here afterwards, and a copy step is a step that
# can be incomplete - shc.exe arrived without the runtime archives it links,
# which no build and no suite could see and only pressing Run revealed.
# Nothing is copied now; the three are simply told where to write.
#
# Absolute, because each sub-make runs in its own directory and a relative path
# would mean three different places.
#
# **bin/ by default, since the binaries are one directory now.** They used to
# land in the checkout root, scattered among the sources; a build that put five
# programs and a runtime there is hard to tell from the tree they were built
# from. One place, named bin, is where they go - and .gitignore has listed it
# for exactly this. Pass BINDIR= to override, as the product step does.
BINDIR ?= $(CURDIR)/bin
OUT := $(abspath $(BINDIR))

.PHONY: all cc1 cxx1 vm6747 sim6747 asm6x masm link lnk6x rts6x shmrt6x shc c2s editor confirm installer bin check clean

# `installer`, which comes after `confirm`: a workspace build checks that what the
# editor drives is beside it, and then packages it (2026-10-05).
all: installer

cc1:
	$(MAKE) -C $(CC1_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/cc1

# `tms6747` as well as `all`: the Shalimar runtime for the C6000 is cpp11's
# output, a directory of .s files the emulator takes beside a program, so
# shalimar's build needs cpp11, so it waits for it: said only in a comment, a
# -j2 build on the Linux box started shalimar first and found no cpp11.exe.
shc: cxx1
	$(MAKE) -C $(SHC_DIR) BINDIR=$(OUT) BUILD=$(OUT)/obj/shc all tms6747 CXX1=$(OUT)/cpp11.exe

# The converter. Not a compiler and nothing links it - the editor runs it over
# the open file from the Language menu - but it is found the same way the
# compilers are, beside the editor, so it is built into the same place.
#
# All four are given an object directory as well as a binary directory now.
# Each Makefile already defaults its own objects outside its checkout; this
# names one place for all four so that a workspace build leaves a single
# directory behind and `clean` is one removal. Compiler-S calls the variable
# BUILD rather than OBJDIR, which is why that line reads differently.
c2s:
	$(MAKE) -C $(C2S_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/c2s

# The C++ compiler, since 3.0, built the way cc1 is: its Makefile takes the
# same two variables. Its headers stay in its own tree - the driver finds
# them beside itself or through the paths compiled into it - so, unlike shc's
# runtime archives, nothing of it has to travel to $(OUT) but the binary.
cxx1:
	$(MAKE) -C $(CXX1_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/cxx1
vm6747:
	$(MAKE) -C $(VM_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/vm6747

asm6x:
	$(MAKE) -C $(ASM_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/asm6x
masm:
	$(MAKE) -C $(MASM_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/masm
link:
	$(MAKE) -C $(LINK_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/link
lnk6x:
	$(MAKE) -C $(LNK6X_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/lnk6x
# Its Makefile names its program vm6747.exe, the emulator's name; TARGET gives it its own.
sim6747:
	$(MAKE) -C $(SIM_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/sim6747 TARGET=$(OUT)/sim6747.exe

# RTS6x is cpp11's and asm6x's output, so it waits for both, as shc waits for cpp11; its libraries,
# Release and Debug, go to lib/rts6x-tms6747, where the editor looks for them (src/toolchain.cpp).
rts6x: cxx1 asm6x
	$(MAKE) -C $(RTS_DIR) CPP11=$(OUT)/cpp11.exe ASM6X=$(OUT)/asm6x.exe OBJDIR=$(OUT)/obj/rts6x BINDIR=$(OUT)/obj/rts6x-bin
	mkdir -p $(OUT)/lib/rts6x-tms6747
	cp $(OUT)/obj/rts6x-bin/rts6x.lib $(OUT)/obj/rts6x-bin/printf6x.lib \
	   $(OUT)/obj/rts6x-bin/rts6xd.lib $(OUT)/obj/rts6x-bin/printf6xd.lib $(OUT)/lib/rts6x-tms6747/

# Shalimar's C6000 runtime packed as libraries beside RTS6x - shmrt6x.lib from shmrt-tms6747, shmrt6xd.lib from
# shmrt-tms6747-debug: asm6x assembles shc's .s, RTS6x's ar6x packs them. The .s stay for the emulator.
shmrt6x: rts6x shc
	for v in shmrt6x:shmrt-tms6747 shmrt6xd:shmrt-tms6747-debug; do lib=$${v%%:*}; dir=$${v#*:}; \
	  rm -rf $(OUT)/obj/$$lib && mkdir -p $(OUT)/obj/$$lib && \
	  $(OUT)/asm6x.exe "$(OUT)/lib/$$dir/*.s" -o $(OUT)/obj/$$lib/ && \
	  rm -f $(OUT)/lib/rts6x-tms6747/$$lib.lib && \
	  $(OUT)/obj/rts6x-bin/ar6x.exe -r $(OUT)/lib/rts6x-tms6747/$$lib.lib $(OUT)/obj/$$lib/*.obj || exit 1; done

# The dependency, said the same way it is said in the other three: the editor
# is built after the things it drives. Nothing of them ends up inside it.
editor: cc1 cxx1 vm6747 sim6747 asm6x masm link lnk6x rts6x shmrt6x shc c2s
	$(MAKE) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/editor

# Asked of RIDE rather than answered here. The editor is the thing that
# knows what it drives - the list is in its own Makefile, beside the code that
# goes looking for them - and this only calls it once all four have been
# built into one place.
confirm: editor
	$(MAKE) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/editor confirm

# Each suite is that project's own, called by the name that project uses -
# both compilers say `test` and only the editor says `check`. Calling `check`
# on all three was written first and failed on the first run, which is the
# argument for running one of these before believing it.
#
# And cc1's `test` is a Linux suite. It compares against gcc and runs x86-64
# binaries, so on a Mac it refuses and names what does run here instead. That
# refusal is cc1 being right, so this asks the host and runs what that host
# can - rather than the alternatives, which are to skip cc1 on a Mac or to
# ignore a failure and lose the real ones with it.
HOST := $(shell uname -s)

check: confirm
ifeq ($(HOST),Darwin)
	cd $(CC1_DIR) && CC1=$(OUT)/c90.exe ./tests/arm64.sh
	cd $(CC1_DIR) && CC1=$(OUT)/c90.exe ./tests/fingerprint.sh
else
	$(MAKE) -C $(CC1_DIR) test
endif
	cd $(CC1_DIR) && CC1=$(OUT)/c90.exe VM=$(OUT)/vm6747.exe ./tests/tms6747.sh
	cd $(CXX1_DIR) && CXX1=$(OUT)/cpp11.exe VM=$(OUT)/vm6747.exe ./tests/tms6747.sh
# The assembler against asm6x's recorded objects, python3 alone.
	cd $(ASM_DIR) && ASM=$(OUT)/asm6x.exe sh tests/run.sh
# And the x86-64 one against ml64's recorded objects, the same way.
	cd $(MASM_DIR) && ASM=$(OUT)/masm.exe sh tests/run.sh
# The linker against link.exe's recorded images, byte for byte. Its bed exits
# 2 when a probe had to be skipped for want of an input - kernel32.lib is
# Microsoft's and is not checked in; `sh tests/probes.sh` brings it back from
# the Windows box - and 1 when an image differed. A skip is not a failure
# here; a difference is.
	cd $(LINK_DIR) && LINK=$(OUT)/link.exe sh tests/run.sh || [ $$? -eq 2 ]
# The C6000 linker against lnk6x's recorded images, the same way and with the
# same two exits: TI's runtime library is the input that is not checked in.
	cd $(LNK6X_DIR) && LNK=$(OUT)/lnk6x.exe sh tests/run.sh || [ $$? -eq 2 ]
# The simulator's machine-code path and its oracle kit, against the sim6747.exe just built.
	cd $(SIM_DIR) && SIM6747=$(OUT)/sim6747.exe sh tests/c6x-all.sh
# LIBDIR too: Compiler-S's examples suite builds a C library from
# Compiler-C/examples, and this is the only place that knows where Compiler-C
# actually is on this machine - it is ~/ansicc on the Linux box. Without it
# that check found nothing and said nothing.
	$(MAKE) -C $(SHC_DIR) SHC=$(OUT)/shalimar.exe CC1=$(OUT)/c90.exe \
	    LIBDIR=$(abspath $(CC1_DIR))/examples/shalimar-library test
# The Shalimar corpus on the emulator, with the runtime cpp11 built.
	$(MAKE) -C $(SHC_DIR) BINDIR=$(OUT) BUILD=$(OUT)/obj/shc CXX1=$(OUT)/cpp11.exe test-tms6747
# The converter's suite is differential and needs both compilers as oracles.
# It is given the two just built into $(OUT), for the same reason the editor's
# is below: those are the ones this build produced, and they are the ones
# whose behaviour the converter's output is being judged against.
	$(MAKE) -C $(C2S_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/c2s test CC1=$(OUT)/c90.exe SHC=$(OUT)/shalimar.exe
# cxx1's own suites, against the binary just built into $(OUT) - its Makefile
# runs them on $(TARGET), which BINDIR names. The differential suites ask the
# host's g++ or clang++ for the answers, so they run wherever the editor does.
	$(MAKE) -C $(CXX1_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/cxx1 test
# The three just built into $(OUT), and not the copies in those repositories'
# own trees. Those are usually the same file and occasionally are not, and the
# occasion is exactly the one worth catching: this build wrote its compilers
# and its converter somewhere, and this is the suite that says whether what it
# wrote works.
#
# Naming the wrong ones does not fail - the editor's suite skips the cases that
# need a compiler and says so quietly - so the count fell from 792 and 232 to
# 686 and 115 and everything still read as green. A suite that skips is not a
# suite that passes.
	$(MAKE) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/editor check CC1=$(OUT)/c90.exe CXX1=$(OUT)/cpp11.exe SHC=$(OUT)/shalimar.exe C2S=$(OUT)/c2s.exe

# The installer is the workspace's last project: after every program is built and
# confirmed, the platform's packager makes it from them - dist/RIDE-$(VER)-linux-x86_64.run
# on Linux, dist/RIDE-$(VER)-macos.pkg on a Mac. NOINSTALLER=1 skips it: the packagers
# pass it when they build the workspace themselves, so neither builds the other.
VER ?= 5.1
installer: confirm
ifneq ($(NOINSTALLER),)
	@echo "installer: skipped (NOINSTALLER)"
else ifeq ($(HOST),Darwin)
	sh packaging/macos/build-pkg.sh $(VER)
else
	BIN=$(OUT) sh packaging/linux/build-run.sh $(VER)
endif

# bin/ is where BINDIR points by default now, so `bin` is just an explicit
# name for the ordinary build - kept so a script or a habit that says `make -f
# workspace.mk bin` still works and lands in the same place.
BIN := bin

bin: all

clean:
	rm -rf $(BIN)
	$(MAKE) -C $(CC1_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/cc1 clean
	$(MAKE) -C $(SHC_DIR) BINDIR=$(OUT) BUILD=$(OUT)/obj/shc clean
	$(MAKE) -C $(C2S_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/c2s clean
	$(MAKE) -C $(CXX1_DIR) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/cxx1 clean
	$(MAKE) BINDIR=$(OUT) OBJDIR=$(OUT)/obj/editor clean
	rm -rf $(OUT)/obj
